### ISSUE TITLE
Lacking documentation for unclear message "Called on an atom..."

### ISSUE THREAD

**Issue by maconard** [grencez/protocon#16]
This particular error appears to be thrown from this file: https://github.com/grencez/protocon/blob/trunk/src/cx/sesp.h

But from looking at the code there I'm at a complete loss for what it is trying to say, and the error doesn't provide a line number or any other debugging information for what could be going wrong.

Sample error:
```
./cx/sesp.h(237) cdr_of_Sesp: Called on an atom...
./cx/syscx.c(27) signal_hook_sysCx: Caught signal: 11
FAILOUT: ./bin/protocon
```

Cheers,

**Comment by grencez** [comment]
What's the file that it's trying to parse?

The AST is represented internally with an S-expression structure. Translated from Lisp into English, this error means that the code is "trying to get the next items of a list, but the given list is not a list at all".

It should probably be a parse error with a line number... which I hear isn't actually giving a number in some cases. One step at a time. 😅

**Comment by maconard** [comment]
It seems you cannot do something like `write: a;` where `a` is a variable array. Is it impossible to allow a process to have write permission to the whole array, as compared to only certain indices based on the process ID (i.e. `write: a[i];`)?

I confirmed that trying to do this is something that causes the "Called on an atom..." error.

**Comment by grencez** [comment]
Yep. It's a pretty deeply rooted assumption in the codebase.

I don't really know how to give anything better than a line number error, so this'll have to suffice for now.
